package java_io;

import java.io.Serializable;

/**
 * serialVersionUID:
 * 
 * In Serialization both the sender and receiver need not to be same and need
 * not be from the same location and need not to use same machine. Persons may
 * be different, locations may be different and machines may be different.
 * 
 * At the time of Serialization JVM will save a unique id with every object.
 * This unique id will be generated by JVM based on .class file. At the time of
 * DeSerialization receiver side JVM will compare object unique id with local
 * .class unique id.
 * 
 * If both are matched then only DeSerialization will be performed otherwise
 * receiver unable to DeSerialize and we'll get RE: InvalidClassException.
 * 
 * This unique identifier is nothing but serialVersionUID.
 * 
 * 
 * 
 * 
 * Note(ENTHUWARE):
 * 
 * 1. When a file is DeSerialized into an object, the class's constructor and
 * instance initializers are not called. So the fields for which no value is
 * available in the serialized file, are initialized to their default values
 * (i.e. number fields to 0, boolean to false, and references to null).
 * 
 * 2. serialVersionUID denotes the version number of the class. If you don't
 * specify serialVersionUID for a class that implements SerializablE, Java
 * compiler automatically adds this field. It computes a value based on the
 * attributes of the class such as the fields and interfaces, and assigns that
 * value to serialVersionUID.
 * 
 * It is used during DeSerialization to verify that the sender and receiver of a
 * serialized object have loaded classes for that object that are compatible
 * with respect to serialization. If the receiver has loaded a class for the
 * object that has a different serialVersionUID than that of the corresponding
 * sender's class, then De\Serialization will result in an
 * InvalidClassException.
 * 
 * 3. If the serialVersionUID for the serialized object and the actual class is
 * same then the DeSerialization completes successfully but any additional
 * fields that are not present in the serialized file are initialized to their
 * default value (as per point 1. above).  Any fields that are missing in the
 * class but are present in the serialized file are ignored.
 * 
 * 
 * 
 * The problems of depending on Default serialVersionUID generated by JVM:
 * 
 * 1) Both sender and receiver should use same JVM with respect to vendor and
 * version. If there is any Incompatibility in JVM versions, then receiver is
 * unable to DeSerialize because of different serialVersionUID's. In this case
 * we'll get RE: InvalidClassException.
 * 
 * 2) After Serialization if we change .class file at receiver side then we
 * can't perform DeSerialization because of miss match in serialVersionUID's of
 * local class of receiver and serialized object. In this case at the time of
 * DeSerialization we'll get RE: InvalidClassException.
 * 
 * 3) To generate serialVersionUID internally JVM will use complex algorithm
 * which may create performance problems.
 * 
 * We can solve this above problems by configuring our own serialVersionUID.
 */

// We can configure serialVersionUID as follows:

public class Serialization_7 implements Serializable {

	private static final long serialVersionUID = 1L;
}
